kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wetpaddle-react-app
  namespace: cb1c00-tools
  annotations:
    description: wetpaddle-react-app
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2022-07-25T05:54:59Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:description': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:output':
            'f:to': {}
          'f:resources':
            'f:limits': {}
            'f:requests': {}
          'f:runPolicy': {}
          'f:source':
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-04-17T23:55:56Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:failedBuildsHistoryLimit': {}
          'f:resources':
            'f:limits':
              'f:cpu': {}
              'f:memory': {}
            'f:requests':
              'f:cpu': {}
              'f:memory': {}
          'f:source':
            'f:contextDir': {}
            'f:dockerfile': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:from': {}
            'f:type': {}
          'f:successfulBuildsHistoryLimit': {}
          'f:triggers': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-06-05T22:55:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'wetpaddle_react:latest'
  resources:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: wetpaddle/Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/WetPaddlers.git'
      ref: dev
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: wetpaddle-app-webhook-secret
  runPolicy: SerialLatestOnly
