apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: wetpaddle-react
  namespace: cb1c00-dev
  labels:
    app: wetpaddle-react
    app-name: wetpaddle-react
    env-id: deploy
    env-name: dev
    github-owner: bcgov
    github-repo: WetPaddlers
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - wetpaddle-react
        from:
          kind: ImageStreamTag
          namespace: cb1c00-tools
          name: 'wetpaddle-react:latest'
    - type: ConfigChange
  selector:
    app: wetpaddle-react
  template:
    metadata:
      labels:
        app: wetpaddle-react
        app-name: wetpaddle-react
        env-id: deploy
        env-name: dev
        github-owner: bcgov
        github-repo: WetPaddlers
    spec:
      replicas: 1
      containers:
        - name: app
          image: wetpaddle-react
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5173
              scheme: HTTP
            initialDelaySeconds: 65
            timeoutSeconds: 20
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5173
              scheme: HTTP
            initialDelaySeconds: 65
            timeoutSeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          ports:
            - containerPort: 5173
              protocol: TCP
          volumeMounts:
            - name: temp-volume
              mountPath: /path/to/mount
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: temp-volume
          emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      minReadySeconds: 5
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  status:
    observedGeneration: 89
    replicas: 1
    updatedReplicas: 1
    readyReplicas: 1
    availableReplicas: 1
    unavailableReplicas: 0
    latestVersion: 52
    details:
      message: config change
      causes:
        - type: ConfigChange
