kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
 name: wetpaddle-react
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-05-24T17:39:04Z'
      fieldsType: FieldsV1
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-05-24T17:39:05Z'
      fieldsType: FieldsV1
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2023-06-07T18:07:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:updatedReplicas': {}
          'f:readyReplicas': {}
          'f:conditions':
            'k:{"type":"Available"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
            'k:{"type":"Progressing"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
          'f:details':
            'f:causes': {}
            'f:message': {}
          'f:replicas': {}
          'f:availableReplicas': {}
          'f:observedGeneration': {}
          'f:unavailableReplicas': {}
          'f:latestVersion': {}
      subresource: status
  namespace: 7068ad-dev
  labels:
    app: wetpaddle-react
    app-name: wetpaddle-react
    env-id: deploy
    env-name: dev
    github-owner: bcgov
    github-repo: WetPaddlers
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 1Gi
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - wetpaddle-react
        from:
          kind: ImageStreamTag
          namespace: cb1c00-dev
          name: 'wetpaddle-react:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentConfig: wetpaddle-react
  template:
    spec:
      volumes:
          emptyDir: {}
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3030
              scheme: HTTP
            initialDelaySeconds: 65
            timeoutSeconds: 20
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          name: app
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3030
              scheme: HTTP
            initialDelaySeconds: 65
            timeoutSeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          env:
          ports:
            - containerPort: 5173
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 89
  details:
    message: config change
    causes:
      - type: ConfigChange
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 52
  updatedReplicas: 1
  replicas: 1
  readyReplicas: 1
